- project:
    templates:
      - openstack-python3-zed-jobs
    check:
      jobs:
        - build-wheel-cache-centos-8-stream:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-bionic:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-focal:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-jammy:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-bindep:
            voting: false
        - requirements-tox-py38-check-uc
        - requirements-tox-py39-check-uc
        - requirements-tox-validate-projects:
            voting: false
        - cross-aodh-py38
        - cross-barbican-py38
        - cross-ceilometer-py38
        - cross-cinder-py38
        - cross-designate-py38
        - cross-glance-py38
        - cross-heat-py38
        - cross-horizon-py38
        - cross-horizon-npm
        - cross-ironic-py38
        - cross-keystone-py38
        - cross-kuryr-py38
        - cross-manila-py38
        - cross-masakari-py38
        - cross-mistral-py38
        - cross-neutron-py38
        - cross-nova-py38
        - cross-placement-py38
        - cross-osvif-py3
        - cross-nova-functional
        - cross-placement-functional-py38
        - cross-octavia-py38
        - cross-osc-tox-docs
        - cross-swift-py38
        - openstack-tox-py38
        - openstacksdk-functional-devstack
        - tempest-full-py3:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    check-arm64:
      jobs:
        - requirements-tox-py38-check-uc-aarch64:
            files:
              - bindep.txt
              - upper-constraints.txt
        - build-wheel-cache-centos-8-stream-arm64:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-bionic-arm64:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-focal-arm64:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-jammy-arm64:
            files:
              - bindep.txt
    gate:
      jobs:
        - build-wheel-cache-centos-8-stream:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-bionic:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-focal:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-jammy:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-py38-check-uc
        - requirements-tox-py39-check-uc
        - cross-cinder-py38
        - cross-designate-py38
        - cross-glance-py38
        - cross-heat-py38
        - cross-horizon-py38
        - cross-horizon-npm
        - cross-ironic-py38
        - cross-keystone-py38
        - cross-kuryr-py38
        - cross-manila-py38
        - cross-masakari-py38
        - cross-neutron-py38
        - cross-nova-py38:
            files: ^upper-constraints.txt$
        - cross-placement-py38:
            files: ^upper-constraints.txt$
        - cross-osvif-py3
        - cross-nova-functional
        - cross-placement-functional-py38
        - cross-octavia-py38
        - cross-osc-tox-docs
        - cross-swift-py38
        - openstack-tox-py38
        - openstacksdk-functional-devstack
        - tempest-full-py3:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    experimental:
      jobs:
        - tempest-pg-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
