- project:
    templates:
      - openstack-python3-ussuri-jobs
    check:
      jobs:
        - build-wheel-mirror-centos-7:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-bionic:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-xenial:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-bindep:
            voting: false
        - requirements-tox-py36-check-uc
        - requirements-tox-validate-projects:
            voting: false
        - cross-cinder-py36
        - cross-glance-py36
        - cross-horizon-py36
        - cross-horizon-npm
        - cross-keystone-py36
        - cross-neutron-py36
        - cross-nova-py36
        - cross-nova-py37
        - cross-nova-functional
        - cross-octavia-py36
        - cross-octavia-py37
        - cross-osc-tox-docs
        - cross-swift-py27
        - cross-swift-py36
        - openstack-tox-py36
        - openstacksdk-functional-devstack
        - neutron-grenade-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - tempest-full-py3:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - grenade-py3:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    gate:
      jobs:
        - build-wheel-mirror-centos-7:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-bionic:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-xenial:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-py36-check-uc
        - cross-cinder-py36
        - cross-glance-py36
        - cross-horizon-py36
        - cross-horizon-npm
        - cross-keystone-py36
        - cross-neutron-py36
        - cross-nova-py36:
            files: ^upper-constraints.txt$
        - cross-nova-py37:
            files: ^upper-constraints.txt$
        - cross-nova-functional
        - cross-octavia-py36
        - cross-octavia-py37
        - cross-osc-tox-docs
        - cross-swift-py27
        - cross-swift-py36
        - openstack-tox-py36
        - openstacksdk-functional-devstack
        - neutron-grenade-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - tempest-full-py3:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - grenade-py3:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    experimental:
      jobs:
        - tempest-pg-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - tempest-full-py3-opensuse15:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$

